// ===== data.js - جميع منتجات كيا وهيونداي (نسخة SVG) =====

const products = [
    // ======================== كيا سبورتاج ========================
    {
        id: 101,
        name: "فلتر زيت - كيا سبورتاج",
        price: 45,
        category: "فلاتر",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        engine: "2.0 / 2.4",
        oem: "26300-35503-KS",
        image: "images/icons/filter.svg",
        stock: 25,
        description: "فلتر زيت أصلي - كيا سبورتاج - ضمان الجودة 100%"
    },
    {
        id: 105,
        name: "مساعدات أمامية - كيا سبورتاج",
        price: 450,
        category: "مساعدات",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "55310-3S000",
        image: "images/icons/shock.svg",
        featured: true,
        isBestSeller: true,
        stock: 12,
        description: "مساعدات أمامية أصلية - كيا سبورتاج"
    },
    {
        id: 107,
        name: "طقم فرامل أمامي - كيا سبورتاج",
        price: 320,
        category: "فرامل",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "58101-3SA00",
        image: "images/icons/brake.svg",
        featured: true,
        isBestSeller: true,
        stock: 15,
        description: "طقم فرامل أمامي (أقراص + فحمات) - كيا سبورتاج"
    },
    {
        id: 102,
        name: "فلتر هواء - كيا سبورتاج",
        price: 65,
        category: "فلاتر",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "28113-3S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 30,
        description: "فلتر هواء محرك أصلي - كيا سبورتاج"
    },
    {
        id: 103,
        name: "فلتر بنزين - كيا سبورتاج",
        price: 55,
        category: "فلاتر",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "31911-2S000",
        image: "images/icons/filter.svg",
        stock: 18,
        description: "فلتر بنزين أصلي - كيا سبورتاج"
    },
    {
        id: 104,
        name: "فلتر مكيف هواء - كيا سبورتاج",
        price: 40,
        category: "فلاتر",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "97133-2S000",
        image: "images/icons/filter.svg",
        stock: 35,
        description: "فلتر مكيف هواء كابينة - كيا سبورتاج"
    },
    {
        id: 106,
        name: "مساعدات خلفية - كيا سبورتاج",
        price: 420,
        category: "مساعدات",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "55311-3S000",
        image: "images/icons/shock.svg",
        featured: true,
        stock: 10,
        description: "مساعدات خلفية أصلية - كيا سبورتاج"
    },
    {
        id: 108,
        name: "طقم فرامل خلفي - كيا سبورتاج",
        price: 290,
        category: "فرامل",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "58102-3SA00",
        image: "images/icons/brake.svg",
        stock: 14,
        description: "طقم فرامل خلفي (أقراص + فحمات) - كيا سبورتاج"
    },
    {
        id: 109,
        name: "بواجي (شمعة احتراق) - كيا سبورتاج",
        price: 120,
        category: "كهرباء",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 40,
        description: "طقم بواجي أصلية 4 حبات - كيا سبورتاج"
    },
    {
        id: 110,
        name: "دينمو - كيا سبورتاج",
        price: 580,
        category: "كهرباء",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "37300-3S000",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 8,
        description: "دينمو سيارة أصلي - كيا سبورتاج - ضمان 6 شهور"
    },
    {
        id: 111,
        name: "بطارية - كيا سبورتاج",
        price: 320,
        category: "كهرباء",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "37110-3S000",
        image: "images/icons/electrical.svg",
        stock: 20,
        description: "بطارية سيارة 70 أمبير - كيا سبورتاج"
    },
    {
        id: 112,
        name: "طرمبة بنزين - كيا سبورتاج",
        price: 350,
        category: "محركات",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "31110-3S000",
        image: "images/icons/engine.svg",
        stock: 9,
        description: "طرمبة بنزين داخلية - كيا سبورتاج"
    },
    {
        id: 113,
        name: "مضخة ماء - كيا سبورتاج",
        price: 280,
        category: "تبريد",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "25100-3S000",
        image: "images/icons/cooling.svg",
        featured: true,
        stock: 11,
        description: "مضخة ماء تبريد المحرك - كيا سبورتاج"
    },
    {
        id: 114,
        name: "ردياتير (مبرد) - كيا سبورتاج",
        price: 550,
        category: "تبريد",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "25310-3S000",
        image: "images/icons/cooling.svg",
        stock: 7,
        description: "ردياتير تبريد محرك أصلي - كيا سبورتاج"
    },
    {
        id: 115,
        name: "صدام أمامي - كيا سبورتاج",
        price: 750,
        category: "هيكل",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "86511-3S000",
        image: "images/icons/body.svg",
        stock: 5,
        description: "صدام أمامي مع شبك - كيا سبورتاج"
    },
    {
        id: 116,
        name: "صدام خلفي - كيا سبورتاج",
        price: 680,
        category: "هيكل",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "86611-3S000",
        image: "images/icons/body.svg",
        stock: 6,
        description: "صدام خلفي - كيا سبورتاج"
    },
    {
        id: 117,
        name: "لمبة أمامية (كشاف) - كيا سبورتاج",
        price: 180,
        category: "كهرباء",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "92101-3S000",
        image: "images/icons/electrical.svg",
        stock: 15,
        description: "لمبة كشاف أمامي يسار/يمين - كيا سبورتاج"
    },
    {
        id: 118,
        name: "مرآة جانبية - كيا سبورتاج",
        price: 220,
        category: "هيكل",
        brand: "كيا",
        model: "سبورتاج",
        year: "2016-2025",
        oem: "87610-3S000",
        image: "images/icons/body.svg",
        stock: 12,
        description: "مرآة جانبية كهربائية - كيا سبورتاج"
    },

    // ======================== كيا سيراتو ========================
    {
        id: 119,
        name: "فلتر زيت - كيا سيراتو",
        price: 40,
        category: "فلاتر",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        engine: "1.6 / 2.0",
        oem: "26300-35503-CE",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 30,
        description: "فلتر زيت أصلي - كيا سيراتو"
    },
    {
        id: 120,
        name: "فلتر هواء - كيا سيراتو",
        price: 60,
        category: "فلاتر",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "28113-1R000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 28,
        description: "فلتر هواء محرك - كيا سيراتو"
    },
    {
        id: 121,
        name: "دينمو - كيا سيراتو",
        price: 550,
        category: "كهرباء",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "37300-2B000",
        image: "images/icons/electrical.svg",
        featured: true,
        isBestSeller: true,
        stock: 9,
        description: "دينمو سيارة أصلي - كيا سيراتو - ضمان 6 شهور"
    },
    {
        id: 122,
        name: "مساعدات أمامية - كيا سيراتو",
        price: 380,
        category: "مساعدات",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "55310-2B000",
        image: "images/icons/shock.svg",
        featured: true,
        stock: 14,
        description: "مساعدات أمامية أصلية - كيا سيراتو"
    },
    {
        id: 123,
        name: "طقم فرامل - كيا سيراتو",
        price: 280,
        category: "فرامل",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "58101-2B000",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 16,
        description: "طقم فرامل أمامي - كيا سيراتو"
    },
    {
        id: 124,
        name: "بواجي - كيا سيراتو",
        price: 110,
        category: "كهرباء",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 35,
        description: "طقم بواجي 4 حبات - كيا سيراتو"
    },
    {
        id: 125,
        name: "طرمبة بنزين - كيا سيراتو",
        price: 320,
        category: "محركات",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "31110-2B000",
        image: "images/icons/engine.svg",
        stock: 10,
        description: "طرمبة بنزين داخلية - كيا سيراتو"
    },
    {
        id: 126,
        name: "مضخة ماء - كيا سيراتو",
        price: 250,
        category: "تبريد",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "25100-2B000",
        image: "images/icons/cooling.svg",
        stock: 12,
        description: "مضخة ماء تبريد - كيا سيراتو"
    },
    {
        id: 127,
        name: "ردياتير - كيا سيراتو",
        price: 480,
        category: "تبريد",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "25310-2B000",
        image: "images/icons/cooling.svg",
        stock: 8,
        description: "ردياتير تبريد محرك - كيا سيراتو"
    },
    {
        id: 128,
        name: "بطارية - كيا سيراتو",
        price: 290,
        category: "كهرباء",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "37110-2B000",
        image: "images/icons/electrical.svg",
        stock: 22,
        description: "بطارية سيارة 60 أمبير - كيا سيراتو"
    },
    {
        id: 129,
        name: "صدام أمامي - كيا سيراتو",
        price: 650,
        category: "هيكل",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "86511-2B000",
        image: "images/icons/body.svg",
        stock: 6,
        description: "صدام أمامي مع شبك - كيا سيراتو"
    },
    {
        id: 130,
        name: "مرآة جانبية - كيا سيراتو",
        price: 190,
        category: "هيكل",
        brand: "كيا",
        model: "سيراتو",
        year: "2013-2025",
        oem: "87610-2B000",
        image: "images/icons/body.svg",
        stock: 14,
        description: "مرآة جانبية كهربائية - كيا سيراتو"
    },

    // ======================== كيا K5 ========================
    {
        id: 131,
        name: "فلتر زيت - كيا K5",
        price: 48,
        category: "فلاتر",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        engine: "2.0 / 2.4",
        oem: "26300-35503-K5",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 28,
        description: "فلتر زيت أصلي - كيا K5"
    },
    {
        id: 132,
        name: "فلتر هواء - كيا K5",
        price: 70,
        category: "فلاتر",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "28113-2S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 25,
        description: "فلتر هواء محرك - كيا K5"
    },
    {
        id: 133,
        name: "دينمو - كيا K5",
        price: 620,
        category: "كهرباء",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "37300-2S000",
        image: "images/icons/electrical.svg",
        featured: true,
        isBestSeller: true,
        stock: 7,
        description: "دينمو سيارة أصلي - كيا K5"
    },
    {
        id: 134,
        name: "بواجي - كيا K5",
        price: 140,
        category: "كهرباء",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 32,
        description: "طقم بواجي 4 حبات - كيا K5"
    },
    {
        id: 135,
        name: "مساعدات - كيا K5",
        price: 420,
        category: "مساعدات",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "55310-2S000",
        image: "images/icons/shock.svg",
        featured: true,
        stock: 11,
        description: "مساعدات أمامية أصلية - كيا K5"
    },
    {
        id: 136,
        name: "طقم فرامل - كيا K5",
        price: 310,
        category: "فرامل",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "58101-2S000",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 13,
        description: "طقم فرامل أمامي - كيا K5"
    },
    {
        id: 137,
        name: "مضخة ماء - كيا K5",
        price: 270,
        category: "تبريد",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "25100-2S000",
        image: "images/icons/cooling.svg",
        stock: 10,
        description: "مضخة ماء تبريد المحرك - كيا K5"
    },
    {
        id: 138,
        name: "بطارية - كيا K5",
        price: 340,
        category: "كهرباء",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "37110-2S000",
        image: "images/icons/electrical.svg",
        stock: 18,
        description: "بطارية سيارة 70 أمبير - كيا K5"
    },
    {
        id: 139,
        name: "صدام أمامي - كيا K5",
        price: 780,
        category: "هيكل",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "86511-2S000",
        image: "images/icons/body.svg",
        stock: 5,
        description: "صدام أمامي - كيا K5"
    },
    {
        id: 140,
        name: "لمبة أمامية - كيا K5",
        price: 200,
        category: "كهرباء",
        brand: "كيا",
        model: "K5",
        year: "2014-2025",
        oem: "92101-2S000",
        image: "images/icons/electrical.svg",
        stock: 12,
        description: "لمبة كشاف أمامي - كيا K5"
    },

    // ======================== كيا سورينتو ========================
    {
        id: 141,
        name: "فلتر زيت - كيا سورينتو",
        price: 55,
        category: "فلاتر",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        engine: "2.2 / 3.3",
        oem: "26300-35503-SO",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 22,
        description: "فلتر زيت أصلي - كيا سورينتو"
    },
    {
        id: 142,
        name: "فلتر هواء - كيا سورينتو",
        price: 75,
        category: "فلاتر",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "28113-3S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 20,
        description: "فلتر هواء محرك - كيا سورينتو"
    },
    {
        id: 143,
        name: "مساعدات أمامية - كيا سورينتو",
        price: 520,
        category: "مساعدات",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "55310-3S500",
        image: "images/icons/shock.svg",
        featured: true,
        isBestSeller: true,
        stock: 9,
        description: "مساعدات أمامية أصلية - كيا سورينتو"
    },
    {
        id: 144,
        name: "دينمو - كيا سورينتو",
        price: 650,
        category: "كهرباء",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "37300-3S500",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 6,
        description: "دينمو سيارة أصلي - كيا سورينتو"
    },
    {
        id: 145,
        name: "طقم فرامل - كيا سورينتو",
        price: 380,
        category: "فرامل",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "58101-3S500",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 12,
        description: "طقم فرامل أمامي - كيا سورينتو"
    },
    {
        id: 146,
        name: "مضخة ماء - كيا سورينتو",
        price: 320,
        category: "تبريد",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "25100-3S500",
        image: "images/icons/cooling.svg",
        stock: 8,
        description: "مضخة ماء تبريد المحرك - كيا سورينتو"
    },
    {
        id: 147,
        name: "ردياتير - كيا سورينتو",
        price: 620,
        category: "تبريد",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "25310-3S500",
        image: "images/icons/cooling.svg",
        stock: 6,
        description: "ردياتير تبريد محرك - كيا سورينتو"
    },
    {
        id: 148,
        name: "بطارية - كيا سورينتو",
        price: 380,
        category: "كهرباء",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "37110-3S500",
        image: "images/icons/electrical.svg",
        stock: 15,
        description: "بطارية سيارة 80 أمبير - كيا سورينتو"
    },
    {
        id: 149,
        name: "صدام أمامي - كيا سورينتو",
        price: 850,
        category: "هيكل",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "86511-3S500",
        image: "images/icons/body.svg",
        stock: 4,
        description: "صدام أمامي مع شبك - كيا سورينتو"
    },
    {
        id: 150,
        name: "مرآة جانبية - كيا سورينتو",
        price: 250,
        category: "هيكل",
        brand: "كيا",
        model: "سورينتو",
        year: "2015-2025",
        oem: "87610-3S500",
        image: "images/icons/body.svg",
        stock: 10,
        description: "مرآة جانبية كهربائية - كيا سورينتو"
    },

    // ======================== كيا بيكانتو ========================
    {
        id: 151,
        name: "فلتر زيت - كيا بيكانتو",
        price: 35,
        category: "فلاتر",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        engine: "1.0 / 1.2",
        oem: "26300-35503-PI",
        image: "images/icons/filter.svg",
        stock: 35,
        description: "فلتر زيت أصلي - كيا بيكانتو"
    },
    {
        id: 152,
        name: "فلتر هواء - كيا بيكانتو",
        price: 50,
        category: "فلاتر",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        oem: "28113-1S000",
        image: "images/icons/filter.svg",
        stock: 30,
        description: "فلتر هواء محرك - كيا بيكانتو"
    },
    {
        id: 153,
        name: "مساعدات - كيا بيكانتو",
        price: 320,
        category: "مساعدات",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        oem: "55310-1S000",
        image: "images/icons/shock.svg",
        stock: 15,
        description: "مساعدات أمامية - كيا بيكانتو"
    },
    {
        id: 154,
        name: "طقم فرامل - كيا بيكانتو",
        price: 240,
        category: "فرامل",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        oem: "58101-1S000",
        image: "images/icons/brake.svg",
        stock: 18,
        description: "طقم فرامل أمامي - كيا بيكانتو"
    },
    {
        id: 155,
        name: "دينمو - كيا بيكانتو",
        price: 480,
        category: "كهرباء",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        oem: "37300-1S000",
        image: "images/icons/electrical.svg",
        stock: 10,
        description: "دينمو سيارة أصلي - كيا بيكانتو"
    },
    {
        id: 156,
        name: "بواجي - كيا بيكانتو",
        price: 90,
        category: "كهرباء",
        brand: "كيا",
        model: "بيكانتو",
        year: "2017-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 40,
        description: "طقم بواجي 4 حبات - كيا بيكانتو"
    },

    // ======================== كيا ريو ========================
    {
        id: 157,
        name: "فلتر زيت - كيا ريو",
        price: 38,
        category: "فلاتر",
        brand: "كيا",
        model: "ريو",
        year: "2015-2025",
        engine: "1.4 / 1.6",
        oem: "26300-35503-RI",
        image: "images/icons/filter.svg",
        stock: 32,
        description: "فلتر زيت أصلي - كيا ريو"
    },
    {
        id: 158,
        name: "فلتر هواء - كيا ريو",
        price: 55,
        category: "فلاتر",
        brand: "كيا",
        model: "ريو",
        year: "2015-2025",
        oem: "28113-1R000",
        image: "images/icons/filter.svg",
        stock: 28,
        description: "فلتر هواء محرك - كيا ريو"
    },
    {
        id: 159,
        name: "مساعدات - كيا ريو",
        price: 350,
        category: "مساعدات",
        brand: "كيا",
        model: "ريو",
        year: "2015-2025",
        oem: "55310-1R000",
        image: "images/icons/shock.svg",
        stock: 14,
        description: "مساعدات أمامية - كيا ريو"
    },
    {
        id: 160,
        name: "طقم فرامل - كيا ريو",
        price: 260,
        category: "فرامل",
        brand: "كيا",
        model: "ريو",
        year: "2015-2025",
        oem: "58101-1R000",
        image: "images/icons/brake.svg",
        stock: 16,
        description: "طقم فرامل أمامي - كيا ريو"
    },
    {
        id: 161,
        name: "دينمو - كيا ريو",
        price: 520,
        category: "كهرباء",
        brand: "كيا",
        model: "ريو",
        year: "2015-2025",
        oem: "37300-1R000",
        image: "images/icons/electrical.svg",
        stock: 9,
        description: "دينمو سيارة أصلي - كيا ريو"
    },

    // ======================== هيونداي النترا ========================
    {
        id: 201,
        name: "فلتر زيت - هيونداي النترا",
        price: 45,
        category: "فلاتر",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        engine: "1.6 / 1.8 / 2.0",
        oem: "26300-35503-EL",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 35,
        description: "فلتر زيت أصلي - هيونداي النترا"
    },
    {
        id: 205,
        name: "بواجي - هيونداي النترا",
        price: 120,
        category: "كهرباء",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 45,
        description: "طقم بواجي أصلية 4 حبات - هيونداي النترا"
    },
    {
        id: 207,
        name: "مساعدات أمامية - هيونداي النترا",
        price: 420,
        category: "مساعدات",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "55310-2R000",
        image: "images/icons/shock.svg",
        featured: true,
        stock: 14,
        description: "مساعدات أمامية أصلية - هيونداي النترا"
    },
    {
        id: 202,
        name: "فلتر هواء - هيونداي النترا",
        price: 65,
        category: "فلاتر",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "28113-1R000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 30,
        description: "فلتر هواء محرك - هيونداي النترا"
    },
    {
        id: 203,
        name: "فلتر مكيف - هيونداي النترا",
        price: 45,
        category: "فلاتر",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "97133-2R000",
        image: "images/icons/filter.svg",
        stock: 38,
        description: "فلتر مكيف هواء كابينة - هيونداي النترا"
    },
    {
        id: 204,
        name: "طقم كلتش - هيونداي النترا",
        price: 780,
        category: "محركات",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        engine: "1.6 / 1.8",
        oem: "41400-1R000",
        image: "images/icons/engine.svg",
        featured: true,
        isBestSeller: true,
        stock: 8,
        description: "طقم كلتش كامل (قابض + قرص + رمان بلي) - هيونداي النترا"
    },
    {
        id: 206,
        name: "دينمو - هيونداي النترا",
        price: 580,
        category: "كهرباء",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "37300-2R000",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 10,
        description: "دينمو سيارة أصلي - هيونداي النترا"
    },
    {
        id: 208,
        name: "مساعدات خلفية - هيونداي النترا",
        price: 390,
        category: "مساعدات",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "55311-2R000",
        image: "images/icons/shock.svg",
        stock: 12,
        description: "مساعدات خلفية أصلية - هيونداي النترا"
    },
    {
        id: 209,
        name: "طقم فرامل أمامي - هيونداي النترا",
        price: 320,
        category: "فرامل",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "58101-2R000",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 18,
        description: "طقم فرامل أمامي (أقراص + فحمات) - هيونداي النترا"
    },
    {
        id: 210,
        name: "طقم فرامل خلفي - هيونداي النترا",
        price: 290,
        category: "فرامل",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "58102-2R000",
        image: "images/icons/brake.svg",
        stock: 16,
        description: "طقم فرامل خلفي - هيونداي النترا"
    },
    {
        id: 211,
        name: "مضخة ماء - هيونداي النترا",
        price: 280,
        category: "تبريد",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "25100-2R000",
        image: "images/icons/cooling.svg",
        stock: 12,
        description: "مضخة ماء تبريد المحرك - هيونداي النترا"
    },
    {
        id: 212,
        name: "ردياتير - هيونداي النترا",
        price: 520,
        category: "تبريد",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "25310-2R000",
        image: "images/icons/cooling.svg",
        stock: 8,
        description: "ردياتير تبريد محرك أصلي - هيونداي النترا"
    },
    {
        id: 213,
        name: "بطارية - هيونداي النترا",
        price: 310,
        category: "كهرباء",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "37110-2R000",
        image: "images/icons/electrical.svg",
        stock: 22,
        description: "بطارية سيارة 60 أمبير - هيونداي النترا"
    },
    {
        id: 214,
        name: "طرمبة بنزين - هيونداي النترا",
        price: 350,
        category: "محركات",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "31110-2R000",
        image: "images/icons/engine.svg",
        stock: 10,
        description: "طرمبة بنزين داخلية - هيونداي النترا"
    },
    {
        id: 215,
        name: "صدام أمامي - هيونداي النترا",
        price: 700,
        category: "هيكل",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "86511-2R000",
        image: "images/icons/body.svg",
        stock: 6,
        description: "صدام أمامي مع شبك - هيونداي النترا"
    },
    {
        id: 216,
        name: "صدام خلفي - هيونداي النترا",
        price: 620,
        category: "هيكل",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "86611-2R000",
        image: "images/icons/body.svg",
        stock: 7,
        description: "صدام خلفي - هيونداي النترا"
    },
    {
        id: 217,
        name: "لمبة أمامية - هيونداي النترا",
        price: 190,
        category: "كهرباء",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "92101-2R000",
        image: "images/icons/electrical.svg",
        stock: 14,
        description: "لمبة كشاف أمامي يسار/يمين - هيونداي النترا"
    },
    {
        id: 218,
        name: "مرآة جانبية - هيونداي النترا",
        price: 210,
        category: "هيكل",
        brand: "هيونداي",
        model: "النترا",
        year: "2011-2025",
        oem: "87610-2R000",
        image: "images/icons/body.svg",
        stock: 13,
        description: "مرآة جانبية كهربائية - هيونداي النترا"
    },

    // ======================== هيونداي توسان ========================
    {
        id: 219,
        name: "فلتر زيت - هيونداي توسان",
        price: 48,
        category: "فلاتر",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        engine: "2.0 / 2.4",
        oem: "26300-35503-TU",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 30,
        description: "فلتر زيت أصلي - هيونداي توسان"
    },
    {
        id: 220,
        name: "فلتر هواء - هيونداي توسان",
        price: 70,
        category: "فلاتر",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "28113-3S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 28,
        description: "فلتر هواء محرك - هيونداي توسان"
    },
    {
        id: 221,
        name: "فلتر مكيف - هيونداي توسان",
        price: 50,
        category: "فلاتر",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "97133-3S000",
        image: "images/icons/filter.svg",
        stock: 32,
        description: "فلتر مكيف هواء كابينة - هيونداي توسان"
    },
    {
        id: 222,
        name: "مساعدات أمامية - هيونداي توسان",
        price: 480,
        category: "مساعدات",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "55310-3S000",
        image: "images/icons/shock.svg",
        featured: true,
        isBestSeller: true,
        stock: 12,
        description: "مساعدات أمامية أصلية - هيونداي توسان"
    },
    {
        id: 223,
        name: "مساعدات خلفية - هيونداي توسان",
        price: 450,
        category: "مساعدات",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "55311-3S000",
        image: "images/icons/shock.svg",
        stock: 10,
        description: "مساعدات خلفية أصلية - هيونداي توسان"
    },
    {
        id: 224,
        name: "طقم فرامل أمامي - هيونداي توسان",
        price: 350,
        category: "فرامل",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "58101-3S000",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 15,
        description: "طقم فرامل أمامي - هيونداي توسان"
    },
    {
        id: 225,
        name: "طقم فرامل خلفي - هيونداي توسان",
        price: 320,
        category: "فرامل",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "58102-3S000",
        image: "images/icons/brake.svg",
        stock: 13,
        description: "طقم فرامل خلفي - هيونداي توسان"
    },
    {
        id: 226,
        name: "دينمو - هيونداي توسان",
        price: 620,
        category: "كهرباء",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "37300-3S000",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 8,
        description: "دينمو سيارة أصلي - هيونداي توسان"
    },
    {
        id: 227,
        name: "بواجي - هيونداي توسان",
        price: 130,
        category: "كهرباء",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 35,
        description: "طقم بواجي 4 حبات - هيونداي توسان"
    },
    {
        id: 228,
        name: "مضخة ماء - هيونداي توسان",
        price: 300,
        category: "تبريد",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "25100-3S000",
        image: "images/icons/cooling.svg",
        featured: true,
        stock: 10,
        description: "مضخة ماء تبريد المحرك - هيونداي توسان"
    },
    {
        id: 229,
        name: "ردياتير - هيونداي توسان",
        price: 580,
        category: "تبريد",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "25310-3S000",
        image: "images/icons/cooling.svg",
        stock: 7,
        description: "ردياتير تبريد محرك - هيونداي توسان"
    },
    {
        id: 230,
        name: "بطارية - هيونداي توسان",
        price: 350,
        category: "كهرباء",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "37110-3S000",
        image: "images/icons/electrical.svg",
        stock: 18,
        description: "بطارية سيارة 70 أمبير - هيونداي توسان"
    },
    {
        id: 231,
        name: "طرمبة بنزين - هيونداي توسان",
        price: 380,
        category: "محركات",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "31110-3S000",
        image: "images/icons/engine.svg",
        stock: 8,
        description: "طرمبة بنزين داخلية - هيونداي توسان"
    },
    {
        id: 232,
        name: "صدام أمامي - هيونداي توسان",
        price: 780,
        category: "هيكل",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "86511-3S000",
        image: "images/icons/body.svg",
        stock: 5,
        description: "صدام أمامي مع شبك - هيونداي توسان"
    },
    {
        id: 233,
        name: "صدام خلفي - هيونداي توسان",
        price: 700,
        category: "هيكل",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "86611-3S000",
        image: "images/icons/body.svg",
        stock: 6,
        description: "صدام خلفي - هيونداي توسان"
    },
    {
        id: 234,
        name: "لمبة أمامية - هيونداي توسان",
        price: 220,
        category: "كهرباء",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "92101-3S000",
        image: "images/icons/electrical.svg",
        stock: 12,
        description: "لمبة كشاف أمامي - هيونداي توسان"
    },
    {
        id: 235,
        name: "مرآة جانبية - هيونداي توسان",
        price: 240,
        category: "هيكل",
        brand: "هيونداي",
        model: "توسان",
        year: "2015-2025",
        oem: "87610-3S000",
        image: "images/icons/body.svg",
        stock: 11,
        description: "مرآة جانبية كهربائية - هيونداي توسان"
    },

    // ======================== هيونداي سوناتا ========================
    {
        id: 236,
        name: "فلتر زيت - هيونداي سوناتا",
        price: 48,
        category: "فلاتر",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        engine: "2.0 / 2.4",
        oem: "26300-35503-SO",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 28,
        description: "فلتر زيت أصلي - هيونداي سوناتا"
    },
    {
        id: 237,
        name: "فلتر هواء - هيونداي سوناتا",
        price: 68,
        category: "فلاتر",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "28113-2S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 25,
        description: "فلتر هواء محرك - هيونداي سوناتا"
    },
    {
        id: 238,
        name: "دينمو - هيونداي سوناتا",
        price: 600,
        category: "كهرباء",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "37300-2S000",
        image: "images/icons/electrical.svg",
        featured: true,
        isBestSeller: true,
        stock: 9,
        description: "دينمو سيارة أصلي - هيونداي سوناتا"
    },
    {
        id: 239,
        name: "مساعدات - هيونداي سوناتا",
        price: 440,
        category: "مساعدات",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "55310-2S000",
        image: "images/icons/shock.svg",
        featured: true,
        stock: 13,
        description: "مساعدات أمامية أصلية - هيونداي سوناتا"
    },
    {
        id: 240,
        name: "طقم فرامل - هيونداي سوناتا",
        price: 340,
        category: "فرامل",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "58101-2S000",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 14,
        description: "طقم فرامل أمامي - هيونداي سوناتا"
    },
    {
        id: 241,
        name: "بواجي - هيونداي سوناتا",
        price: 140,
        category: "كهرباء",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 30,
        description: "طقم بواجي 4 حبات - هيونداي سوناتا"
    },
    {
        id: 242,
        name: "مضخة ماء - هيونداي سوناتا",
        price: 290,
        category: "تبريد",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "25100-2S000",
        image: "images/icons/cooling.svg",
        stock: 11,
        description: "مضخة ماء تبريد المحرك - هيونداي سوناتا"
    },
    {
        id: 243,
        name: "بطارية - هيونداي سوناتا",
        price: 330,
        category: "كهرباء",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "37110-2S000",
        image: "images/icons/electrical.svg",
        stock: 20,
        description: "بطارية سيارة 70 أمبير - هيونداي سوناتا"
    },
    {
        id: 244,
        name: "صدام أمامي - هيونداي سوناتا",
        price: 750,
        category: "هيكل",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "86511-2S000",
        image: "images/icons/body.svg",
        stock: 5,
        description: "صدام أمامي مع شبك - هيونداي سوناتا"
    },
    {
        id: 245,
        name: "مرآة جانبية - هيونداي سوناتا",
        price: 230,
        category: "هيكل",
        brand: "هيونداي",
        model: "سوناتا",
        year: "2014-2025",
        oem: "87610-2S000",
        image: "images/icons/body.svg",
        stock: 12,
        description: "مرآة جانبية كهربائية - هيونداي سوناتا"
    },

    // ======================== هيونداي سانتافي ========================
    {
        id: 246,
        name: "فلتر زيت - هيونداي سانتافي",
        price: 55,
        category: "فلاتر",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        engine: "2.2 / 3.3",
        oem: "26300-35503-SA",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 25,
        description: "فلتر زيت أصلي - هيونداي سانتافي"
    },
    {
        id: 247,
        name: "فلتر هواء - هيونداي سانتافي",
        price: 80,
        category: "فلاتر",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "28113-3S000",
        image: "images/icons/filter.svg",
        featured: true,
        stock: 22,
        description: "فلتر هواء محرك - هيونداي سانتافي"
    },
    {
        id: 248,
        name: "مساعدات - هيونداي سانتافي",
        price: 550,
        category: "مساعدات",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "55310-3S500",
        image: "images/icons/shock.svg",
        featured: true,
        isBestSeller: true,
        stock: 10,
        description: "مساعدات أمامية أصلية - هيونداي سانتافي"
    },
    {
        id: 249,
        name: "دينمو - هيونداي سانتافي",
        price: 680,
        category: "كهرباء",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "37300-3S500",
        image: "images/icons/electrical.svg",
        featured: true,
        stock: 7,
        description: "دينمو سيارة أصلي - هيونداي سانتافي"
    },
    {
        id: 250,
        name: "طقم فرامل - هيونداي سانتافي",
        price: 400,
        category: "فرامل",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "58101-3S500",
        image: "images/icons/brake.svg",
        featured: true,
        stock: 11,
        description: "طقم فرامل أمامي - هيونداي سانتافي"
    },
    {
        id: 251,
        name: "مضخة ماء - هيونداي سانتافي",
        price: 340,
        category: "تبريد",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "25100-3S500",
        image: "images/icons/cooling.svg",
        stock: 8,
        description: "مضخة ماء تبريد المحرك - هيونداي سانتافي"
    },
    {
        id: 252,
        name: "ردياتير - هيونداي سانتافي",
        price: 650,
        category: "تبريد",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "25310-3S500",
        image: "images/icons/cooling.svg",
        stock: 6,
        description: "ردياتير تبريد محرك - هيونداي سانتافي"
    },
    {
        id: 253,
        name: "بطارية - هيونداي سانتافي",
        price: 400,
        category: "كهرباء",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "37110-3S500",
        image: "images/icons/electrical.svg",
        stock: 15,
        description: "بطارية سيارة 80 أمبير - هيونداي سانتافي"
    },
    {
        id: 254,
        name: "صدام أمامي - هيونداي سانتافي",
        price: 850,
        category: "هيكل",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "86511-3S500",
        image: "images/icons/body.svg",
        stock: 4,
        description: "صدام أمامي مع شبك - هيونداي سانتافي"
    },
    {
        id: 255,
        name: "مرآة جانبية - هيونداي سانتافي",
        price: 280,
        category: "هيكل",
        brand: "هيونداي",
        model: "سانتافي",
        year: "2015-2025",
        oem: "87610-3S500",
        image: "images/icons/body.svg",
        stock: 9,
        description: "مرآة جانبية كهربائية - هيونداي سانتافي"
    },

    // ======================== هيونداي اكسنت ========================
    {
        id: 256,
        name: "فلتر زيت - هيونداي اكسنت",
        price: 35,
        category: "فلاتر",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        engine: "1.4 / 1.6",
        oem: "26300-35503-AC",
        image: "images/icons/filter.svg",
        stock: 35,
        description: "فلتر زيت أصلي - هيونداي اكسنت"
    },
    {
        id: 257,
        name: "فلتر هواء - هيونداي اكسنت",
        price: 50,
        category: "فلاتر",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        oem: "28113-1R000",
        image: "images/icons/filter.svg",
        stock: 30,
        description: "فلتر هواء محرك - هيونداي اكسنت"
    },
    {
        id: 258,
        name: "مساعدات - هيونداي اكسنت",
        price: 320,
        category: "مساعدات",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        oem: "55310-1R000",
        image: "images/icons/shock.svg",
        stock: 15,
        description: "مساعدات أمامية - هيونداي اكسنت"
    },
    {
        id: 259,
        name: "طقم فرامل - هيونداي اكسنت",
        price: 250,
        category: "فرامل",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        oem: "58101-1R000",
        image: "images/icons/brake.svg",
        stock: 18,
        description: "طقم فرامل أمامي - هيونداي اكسنت"
    },
    {
        id: 260,
        name: "دينمو - هيونداي اكسنت",
        price: 500,
        category: "كهرباء",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        oem: "37300-1R000",
        image: "images/icons/electrical.svg",
        stock: 10,
        description: "دينمو سيارة أصلي - هيونداي اكسنت"
    },
    {
        id: 261,
        name: "بواجي - هيونداي اكسنت",
        price: 100,
        category: "كهرباء",
        brand: "هيونداي",
        model: "اكسنت",
        year: "2015-2025",
        oem: "18854-10070",
        image: "images/icons/electrical.svg",
        stock: 40,
        description: "طقم بواجي 4 حبات - هيونداي اكسنت"
    },

    // ======================== هيونداي ازيرا ========================
    {
        id: 262,
        name: "فلتر زيت - هيونداي ازيرا",
        price: 60,
        category: "فلاتر",
        brand: "هيونداي",
        model: "ازيرا",
        year: "2016-2025",
        engine: "3.0 / 3.3",
        oem: "26300-35503-AZ",
        image: "images/icons/filter.svg",
        stock: 20,
        description: "فلتر زيت أصلي - هيونداي ازيرا"
    },
    {
        id: 263,
        name: "فلتر هواء - هيونداي ازيرا",
        price: 85,
        category: "فلاتر",
        brand: "هيونداي",
        model: "ازيرا",
        year: "2016-2025",
        oem: "28113-3S000",
        image: "images/icons/filter.svg",
        stock: 18,
        description: "فلتر هواء محرك - هيونداي ازيرا"
    },
    {
        id: 264,
        name: "مساعدات - هيونداي ازيرا",
        price: 580,
        category: "مساعدات",
        brand: "هيونداي",
        model: "ازيرا",
        year: "2016-2025",
        oem: "55310-3S600",
        image: "images/icons/shock.svg",
        stock: 8,
        description: "مساعدات أمامية - هيونداي ازيرا"
    },
    {
        id: 265,
        name: "دينمو - هيونداي ازيرا",
        price: 720,
        category: "كهرباء",
        brand: "هيونداي",
        model: "ازيرا",
        year: "2016-2025",
        oem: "37300-3S600",
        image: "images/icons/electrical.svg",
        stock: 6,
        description: "دينمو سيارة أصلي - هيونداي ازيرا"
    },
    {
        id: 266,
        name: "طقم فرامل - هيونداي ازيرا",
        price: 450,
        category: "فرامل",
        brand: "هيونداي",
        model: "ازيرا",
        year: "2016-2025",
        oem: "58101-3S600",
        image: "images/icons/brake.svg",
        stock: 9,
        description: "طقم فرامل أمامي - هيونداي ازيرا"
    }
];

// ======================== دوال مساعدة ========================

function getAllProducts() {
    return products;
}

function getKiaProducts() {
    return products.filter(p => p.brand === "كيا");
}

function getHyundaiProducts() {
    return products.filter(p => p.brand === "هيونداي");
}

function getProductById(id) {
    return products.find(p => p.id === parseInt(id));
}

function getFeaturedProducts() {
    return products.filter(p => p.featured === true);
}

function getNewProducts() {
    return products.filter(p => p.isNew === true);
}

function getBestSellers() {
    return products.filter(p => p.isBestSeller === true);
}

function searchProducts(term) {
    term = term.toLowerCase();
    return products.filter(p => 
        p.name.toLowerCase().includes(term) ||
        p.oem.toLowerCase().includes(term) ||
        p.brand.toLowerCase().includes(term) ||
        p.model.toLowerCase().includes(term) ||
        p.category.toLowerCase().includes(term)
    );
}

function getProductsByBrandAndModel(brand, model) {
    return products.filter(p => 
        p.brand === brand && 
        p.model.toLowerCase().includes(model.toLowerCase())
    );
}

function getProductsByCategory(category) {
    return products.filter(p => p.category === category);
}

function getProductsByPrice(min, max) {
    return products.filter(p => p.price >= min && p.price <= max);
}

function getProductsStats() {
    return {
        total: products.length,
        kia: products.filter(p => p.brand === "كيا").length,
        hyundai: products.filter(p => p.brand === "هيونداي").length,
        categories: {
            filters: products.filter(p => p.category === "فلاتر").length,
            shocks: products.filter(p => p.category === "مساعدات").length,
            brakes: products.filter(p => p.category === "فرامل").length,
            electrical: products.filter(p => p.category === "كهرباء").length,
            engine: products.filter(p => p.category === "محركات").length,
            cooling: products.filter(p => p.category === "تبريد").length,
            body: products.filter(p => p.category === "هيكل").length
        }
    };
}